# Generated by Django 5.2 on 2025-04-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('niveau', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
