# Generated by Django 5.2 on 2025-04-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('professor', 'Professeur'), ('student', 'Eleve'), ('admin', 'Administrateur'), ('tutor', 'Tuteur')], max_length=100),
        ),
    ]
