# Generated by Django 5.2 on 2025-04-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='creat_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='note',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='note',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='valeur',
        ),
    ]
