# Generated by Django 5.2 on 2025-04-26 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0001_initial'),
        ('matiere', '0002_remove_matiere_coefficient_matiere_poid_note_compos_and_more'),
        ('note', '0002_remove_note_creat_at_remove_note_libelle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCompos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_note_compos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_enreg', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.evaluation')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='NoteCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_note_cours_orale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valeur_note_cours_ecrite', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date_enreg', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.evaluation')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
