# Generated by Django 5.2 on 2025-04-24 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_schoolmanager_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolManager',
            new_name='SchoolManagers',
        ),
    ]
