# Generated by Django 5.2 on 2025-04-24 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classe.classes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.subjects')),
            ],
        ),
    ]
