# Generated by Django 5.2 on 2025-04-24 11:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='phone_nuber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+224', max_length=128, region=None, unique=True),
        ),
    ]
